import { StrictMode, useEffect, useMemo, useState, type ReactElement } from 'react';
import { createRoot } from 'react-dom/client';
import '@douyinfe/semi-ui/react19-adapter';
import { Button, Input, Layout, Modal, Nav, Tag, Toast, Typography } from '@douyinfe/semi-ui';
import { IconAlertTriangle, IconArrowRight, IconFile, IconFolder, IconHistogram, IconHome, IconMoon, IconPlay, IconPlus, IconRefresh, IconSearch, IconSetting, IconStop, IconSun, IconUpload } from '@douyinfe/semi-icons';
import '../node_modules/@douyinfe/semi-ui/dist/css/semi.css';
import './styles.css';

type Section = 'overview' | 'projects' | 'troubleshooting' | 'logs' | 'reports' | 'settings';
type Status = 'stopped' | 'starting' | 'running' | 'restarting' | 'crashed';
interface Command { executable: string; args: string[]; }
interface Application { id: string; projectId: string; name: string; cwd: string; command: Command; status: Status; }
interface Project { id: string; name: string; path: string; createdAt: string; }
interface EventItem { id: string; type: string; occurredAt: string; detail: Record<string, unknown>; }
interface PreviewApplication { key: string; origin: string; name: string; cwd: string; command: Command; restartPolicy: unknown; logPolicy: unknown; warnings: { field: string; reason: string }[]; }
interface Preview { root: string; projectName: string; applications: PreviewApplication[]; warnings: { field: string; reason: string }[]; }
interface LogLine { at: string; stream: 'stdout' | 'stderr'; line: string; }

const copy: Record<Section, { title: string; eyebrow: string }> = {
  overview: { title: '运行总览', eyebrow: '本机 Node.js 应用运行状态一目了然' },
  projects: { title: '项目', eyebrow: '导入、配置并管理本机工作区' },
  troubleshooting: { title: '排障中心', eyebrow: '先处理异常，再深入查看事件与日志' },
  logs: { title: '实时日志', eyebrow: '原始日志保留在本机文件中，显示内容已脱敏' },
  reports: { title: '报表', eyebrow: '基于 24 小时本机聚合数据观察运行趋势' },
  settings: { title: '设置', eyebrow: '本机守护进程和数据保留策略' }
};

function DockyardApp(): ReactElement {
  const [section, setSection] = useState<Section>('overview');
  const [dark, setDark] = useState(false);
  const [apps, setApps] = useState<Application[]>([]);
  const [projects, setProjects] = useState<Project[]>([]);
  const [events, setEvents] = useState<EventItem[]>([]);
  const [logs, setLogs] = useState<LogLine[]>([]);
  const [selectedId, setSelectedId] = useState('');
  const [scanOpen, setScanOpen] = useState(false);
  const [path, setPath] = useState('');
  const [preview, setPreview] = useState<Preview | null>(null);
  const [busy, setBusy] = useState(false);
  const [pendingAction, setPendingAction] = useState<{ app: Application; operation: 'stop' | 'restart' } | null>(null);
  const [query, setQuery] = useState('');
  const selected = apps.find((app) => app.id === selectedId) ?? apps[0];
  const crashed = apps.filter((app) => app.status === 'crashed');
  const running = apps.filter((app) => app.status === 'running');
  const filtered = useMemo(() => apps.filter((app) => app.name.toLowerCase().includes(query.toLowerCase())), [apps, query]);
  const projectById = useMemo(() => new Map(projects.map((project) => [project.id, project])), [projects]);

  const refresh = async () => {
    try {
      const [applicationResult, projectResult] = await Promise.all([api<{ applications: Application[] }>('/api/applications'), api<{ projects: Project[] }>('/api/projects')]);
      setApps(applicationResult.applications); setProjects(projectResult.projects);
      setSelectedId((current) => current || applicationResult.applications[0]?.id || '');
    } catch { Toast.error('无法连接本机守护进程。'); }
  };
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 4_000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { if (!selected || section !== 'troubleshooting') return; void api<{ events: EventItem[] }>(`/api/applications/${selected.id}/events`).then((result) => setEvents(result.events)).catch(() => setEvents([])); }, [selected?.id, section]);
  useEffect(() => {
    if (!selected || section !== 'logs') return;
    setLogs([]); const source = new EventSource(`/api/applications/${selected.id}/logs/tail?stream=stdout`);
    source.onmessage = (event) => setLogs((current) => [...current.slice(-249), JSON.parse(event.data) as LogLine]);
    source.onerror = () => source.close(); return () => source.close();
  }, [selected?.id, section]);

  const chooseDirectory = async () => { setBusy(true); try { const result = await api<{ path: string | null }>('/api/system/select-directory', { method: 'POST' }); if (result.path) setPath(result.path); } catch (error) { Toast.error(errorMessage(error)); } finally { setBusy(false); } };
  const scan = async () => { if (!path.trim()) return Toast.warning('请选择或输入项目目录。'); setBusy(true); try { setPreview(await api<Preview>('/api/projects/scan', { method: 'POST', body: JSON.stringify({ path, includePm2: true }) })); } catch (error) { Toast.error(errorMessage(error)); } finally { setBusy(false); } };
  const importPreview = async () => { if (!preview) return; setBusy(true); try { await api('/api/projects/import', { method: 'POST', body: JSON.stringify({ path: preview.root, name: preview.projectName, applications: preview.applications }) }); Toast.success('项目已导入。'); setScanOpen(false); setPreview(null); await refresh(); } catch (error) { Toast.error(errorMessage(error)); } finally { setBusy(false); } };
  const executeAction = async (app: Application, operation: 'start' | 'stop' | 'restart') => { try { await api(`/api/applications/${encodeURIComponent(app.id)}/${operation}`, { method: 'POST' }); await refresh(); } catch (error) { Toast.error(errorMessage(error)); } };
  const action = (app: Application, operation: 'start' | 'stop' | 'restart') => { if (operation === 'start') void executeAction(app, operation); else setPendingAction({ app, operation }); };
  const openScan = () => { setPreview(null); setScanOpen(true); };
  const navigate = (target: Section) => { setSection(target); if (target === 'logs' || target === 'troubleshooting') setSelectedId(selected?.id ?? apps[0]?.id ?? ''); };

  const nav = [{ itemKey: 'overview', text: '运行总览', icon: <IconHome /> }, { itemKey: 'projects', text: '项目', icon: <IconFolder /> }, { itemKey: 'troubleshooting', text: '排障中心', icon: <IconAlertTriangle /> }, { itemKey: 'logs', text: '日志', icon: <IconFile /> }, { itemKey: 'reports', text: '报表', icon: <IconHistogram /> }];
  return <div className={dark ? 'semi-always-dark app-theme' : 'semi-always-light app-theme'}><Layout className="app-shell"><Layout.Sider className="app-sider"><div className="brand"><span className="brand-mark">▰</span><span>Dockyard</span></div><Nav className="primary-nav" selectedKeys={[section]} onSelect={(item) => navigate(item.itemKey as Section)} items={nav} /><div className="sider-spacer" /><Nav className="settings-nav" selectedKeys={section === 'settings' ? ['settings'] : []} onSelect={() => navigate('settings')} items={[{ itemKey: 'settings', text: '设置', icon: <IconSetting /> }]} /></Layout.Sider><Layout className="app-main"><Layout.Header className="app-topbar"><div className="topbar-note"><span className="pulse" />本机服务正常</div><Button theme="borderless" icon={dark ? <IconSun /> : <IconMoon />} onClick={() => setDark((value) => !value)} /></Layout.Header><Layout.Content className="app-content"><header className="page-heading"><div><Typography.Title heading={2}>{copy[section].title}</Typography.Title><Typography.Text type="tertiary">{copy[section].eyebrow}</Typography.Text></div>{section !== 'settings' && <Button theme="solid" size="large" icon={<IconPlus />} onClick={openScan}>添加项目</Button>}</header>{section === 'overview' && <Overview apps={apps} projects={projects} running={running} crashed={crashed} onScan={openScan} onNavigate={navigate} onAction={action} projectById={projectById} />}{section === 'projects' && <ProjectsView apps={filtered} projects={projects} query={query} onQuery={setQuery} onScan={openScan} onAction={action} projectById={projectById} />}{section === 'troubleshooting' && <Troubleshooting apps={crashed} selected={selected} events={events} onSelect={setSelectedId} onAction={action} onNavigate={navigate} />}{section === 'logs' && <LogsView apps={apps} selected={selected} logs={logs} onSelect={setSelectedId} />}{section === 'reports' && <ReportsView apps={apps} running={running} crashed={crashed} />}{section === 'settings' && <SettingsView />}</Layout.Content></Layout></Layout><ScanModal visible={scanOpen} path={path} preview={preview} busy={busy} onPath={setPath} onChoose={() => void chooseDirectory()} onScan={() => void scan()} onImport={() => void importPreview()} onClose={() => { setScanOpen(false); setPreview(null); }} /><Modal title={pendingAction?.operation === 'stop' ? '停止应用' : '重启应用'} visible={Boolean(pendingAction)} onCancel={() => setPendingAction(null)} footer={<><Button onClick={() => setPendingAction(null)}>取消</Button><Button theme="solid" type={pendingAction?.operation === 'stop' ? 'danger' : 'primary'} onClick={() => { if (pendingAction) void executeAction(pendingAction.app, pendingAction.operation); setPendingAction(null); }}>{pendingAction?.operation === 'stop' ? '确认停止' : '确认重启'}</Button></>}>{pendingAction && <Typography.Paragraph>确认要{pendingAction.operation === 'stop' ? '停止' : '重启'} <b>{pendingAction.app.name}</b> 吗？守护进程会记录此次生命周期操作。</Typography.Paragraph>}</Modal></div>;
}

function Overview({ apps, projects, running, crashed, onScan, onNavigate, onAction, projectById }: { apps: Application[]; projects: Project[]; running: Application[]; crashed: Application[]; onScan: () => void; onNavigate: (section: Section) => void; onAction: (app: Application, operation: 'start' | 'stop' | 'restart') => void; projectById: Map<string, Project> }): ReactElement {
  if (!apps.length) return <section className="onboarding"><div className="onboarding-art"><IconFolder size="extra-large" /></div><div><Typography.Title heading={3}>从第一个本机项目开始</Typography.Title><Typography.Paragraph type="tertiary">Dockyard 会扫描 package.json 和静态 PM2 配置，预览后再保存。它不会执行扫描到的配置文件。</Typography.Paragraph><Button theme="solid" size="large" icon={<IconSearch />} onClick={onScan}>扫描项目目录</Button></div><ol><li><b>选择目录</b><span>使用系统文件对话框或输入绝对路径</span></li><li><b>审核候选项</b><span>确认命令、工作目录和 PM2 告警</span></li><li><b>开始托管</b><span>由守护进程统一管理生命周期和日志</span></li></ol></section>;
  return <><section className="stat-grid"><StatCard label="托管项目" value={projects.length} accent="blue" icon={<IconFolder />} /><StatCard label="运行应用" value={running.length} accent="green" icon={<IconPlay />} /><StatCard label="需排障" value={crashed.length} accent="red" icon={<IconAlertTriangle />} /><StatCard label="本机日志流" value="实时" accent="violet" icon={<IconHistogram />} /></section>{crashed.length > 0 ? <section className="attention-banner"><span><IconAlertTriangle /> <b>{crashed.length} 个应用需要排障</b><small>已暂停自动恢复或异常退出，打开事件时间线查看原因。</small></span><Button theme="solid" type="danger" onClick={() => onNavigate('troubleshooting')}>查看原因 <IconArrowRight /></Button></section> : <section className="healthy-banner"><span className="pulse" /><b>当前没有崩溃的应用</b><Typography.Text type="tertiary">守护进程持续观察已导入的本机进程。</Typography.Text></section>}<section className="split-grid"><div className="surface"><div className="surface-heading"><div><Typography.Title heading={5}>应用状态</Typography.Title><Typography.Text type="tertiary">实时来自本机守护进程</Typography.Text></div><Button theme="borderless" onClick={() => onNavigate('projects')}>查看全部</Button></div><ApplicationTable apps={apps.slice(0, 5)} onAction={onAction} projectById={projectById} /></div><div className="surface activity"><div className="surface-heading"><div><Typography.Title heading={5}>需要关注</Typography.Title><Typography.Text type="tertiary">先处理异常，再阅读完整日志</Typography.Text></div></div>{crashed.length ? crashed.map((app) => <div className="attention-item" key={app.id}><Tag color="red">crashed</Tag><div><b>{app.name}</b><span>{app.cwd}</span></div><Button size="small" onClick={() => onNavigate('troubleshooting')}>诊断</Button></div>) : <EmptyHint icon={<IconHistogram />} title="运行平稳" text="启动应用后，这里会汇总崩溃和重启提醒。" />}</div></section></>;
}

function ProjectsView({ apps, projects, query, onQuery, onScan, onAction, projectById }: { apps: Application[]; projects: Project[]; query: string; onQuery: (query: string) => void; onScan: () => void; onAction: (app: Application, operation: 'start' | 'stop' | 'restart') => void; projectById: Map<string, Project> }): ReactElement { return <><section className="import-callout"><div className="callout-icon"><IconUpload /></div><div><b>添加一个本机目录</b><Typography.Text type="tertiary">通过系统目录选择器扫描 package.json、工作区和静态 PM2 配置。</Typography.Text></div><Button theme="solid" icon={<IconSearch />} onClick={onScan}>扫描项目</Button></section><section className="surface"><div className="surface-heading"><div><Typography.Title heading={5}>应用目录</Typography.Title><Typography.Text type="tertiary">{projects.length} 个项目 · {apps.length} 个应用</Typography.Text></div><Input prefix={<IconSearch />} value={query} onChange={onQuery} placeholder="按名称搜索应用" className="search-input" /></div>{apps.length ? <ApplicationTable apps={apps} onAction={onAction} projectById={projectById} /> : <EmptyHint icon={<IconFolder />} title="还没有匹配的应用" text="扫描并导入一个本机项目后，它会显示在这里。" />}</section></> }

function Troubleshooting({ apps, selected, events, onSelect, onAction, onNavigate }: { apps: Application[]; selected?: Application; events: EventItem[]; onSelect: (id: string) => void; onAction: (app: Application, operation: 'start' | 'stop' | 'restart') => void; onNavigate: (section: Section) => void }): ReactElement { return <section className="diagnostics-grid"><div className="surface"><div className="surface-heading"><div><Typography.Title heading={5}>崩溃队列</Typography.Title><Typography.Text type="tertiary">达到重试预算的应用会保留在这里。</Typography.Text></div></div>{apps.length ? apps.map((app) => <button className={`crash-row ${selected?.id === app.id ? 'selected' : ''}`} key={app.id} onClick={() => onSelect(app.id)}><Tag color="red">crashed</Tag><span><b>{app.name}</b><small>{app.cwd}</small></span><IconArrowRight /></button>) : <EmptyHint icon={<IconAlertTriangle />} title="没有待处理的崩溃" text="一旦应用因策略暂停，Dockyard 会在这里说明原因。" />}</div><div className="surface"><div className="surface-heading"><div><Typography.Title heading={5}>生命周期时间线</Typography.Title><Typography.Text type="tertiary">{selected ? selected.name : '选择一个异常应用'}</Typography.Text></div>{selected && <Button size="small" onClick={() => onNavigate('logs')}>打开日志</Button>}</div>{selected && events.length ? <div className="timeline">{events.map((event) => <div className="timeline-item" key={event.id}><span className="timeline-dot" /><div><b>{event.type}</b><small>{new Date(event.occurredAt).toLocaleString()}</small><code>{Object.entries(event.detail).map(([key, value]) => `${key}: ${String(value)}`).join(' · ')}</code></div></div>)}</div> : <EmptyHint icon={<IconRefresh />} title="暂无可显示的事件" text="启动、退出和重启策略决定都会记录在这里。" />}{selected && <div className="panel-actions"><Button theme="solid" icon={<IconRefresh />} onClick={() => onAction(selected, 'restart')}>重启应用</Button><Button onClick={() => onNavigate('logs')}>检查实时日志</Button></div>}</div></section> }

function LogsView({ apps, selected, logs, onSelect }: { apps: Application[]; selected?: Application; logs: LogLine[]; onSelect: (id: string) => void }): ReactElement { return <section className="logs-layout"><div className="surface log-controls"><Typography.Title heading={5}>选择应用</Typography.Title>{apps.map((app) => <button key={app.id} onClick={() => onSelect(app.id)} className={`log-app ${selected?.id === app.id ? 'selected' : ''}`}><span className={`status-dot ${app.status}`} /><span><b>{app.name}</b><small>{app.status}</small></span></button>)}{!apps.length && <Typography.Text type="tertiary">先在项目页导入应用。</Typography.Text>}</div><div className="surface terminal"><div className="surface-heading"><div><Typography.Title heading={5}>{selected ? `${selected.name} · stdout` : '实时输出'}</Typography.Title><Typography.Text type="tertiary">仅显示脱敏后的日志行</Typography.Text></div><Tag color="green">live</Tag></div><div className="terminal-body">{logs.length ? logs.map((line, index) => <div key={`${line.at}-${index}`}><time>{new Date(line.at).toLocaleTimeString()}</time><span>{line.line || ' '}</span></div>) : <span className="terminal-empty">{selected ? '正在等待新的 stdout 输出…' : '请选择一个应用开始跟随日志。'}</span>}</div></div></section> }

function ReportsView({ apps, running, crashed }: { apps: Application[]; running: Application[]; crashed: Application[] }): ReactElement { return <><section className="stat-grid"><StatCard label="总应用数" value={apps.length} accent="blue" icon={<IconFolder />} /><StatCard label="当前运行" value={running.length} accent="green" icon={<IconPlay />} /><StatCard label="崩溃队列" value={crashed.length} accent="red" icon={<IconAlertTriangle />} /><StatCard label="采样窗口" value="24h" accent="violet" icon={<IconHistogram />} /></section><section className="surface report-surface"><div><Typography.Title heading={5}>资源与可用性</Typography.Title><Typography.Paragraph type="tertiary">Dockyard 只保留本机聚合元数据。导入并运行应用后，可在此查看连续采样的运行时长、重启次数和资源趋势。</Typography.Paragraph></div><div className="report-bars"><span style={{ height: '35%' }} /><span style={{ height: '55%' }} /><span style={{ height: '42%' }} /><span style={{ height: '74%' }} /><span style={{ height: '61%' }} /><span style={{ height: '85%' }} /><span style={{ height: '58%' }} /></div></section></> }

function SettingsView(): ReactElement { return <section className="settings-grid"><div className="surface"><Typography.Title heading={5}>本机守护进程</Typography.Title><dl><dt>绑定地址</dt><dd>127.0.0.1:4318</dd><dt>进程所有者</dt><dd>Dockyard daemon</dd><dt>日志位置</dt><dd>本机状态目录 · 文件追加存储</dd></dl></div><div className="surface"><Typography.Title heading={5}>安全边界</Typography.Title><Typography.Paragraph type="tertiary">项目扫描只读取静态清单与声明式 PM2 配置；目录选择和进程生命周期都经由本机守护进程执行。显示到 UI 的日志和命令会脱敏。</Typography.Paragraph></div></section> }

function ScanModal({ visible, path, preview, busy, onPath, onChoose, onScan, onImport, onClose }: { visible: boolean; path: string; preview: Preview | null; busy: boolean; onPath: (path: string) => void; onChoose: () => void; onScan: () => void; onImport: () => void; onClose: () => void }): ReactElement { return <Modal title="添加本机项目" visible={visible} onCancel={onClose} footer={<><Button onClick={onClose}>取消</Button><Button theme="solid" loading={busy} onClick={preview ? onImport : onScan}>{preview ? '导入已审核的候选项' : '扫描目录'}</Button></>}><Typography.Paragraph type="tertiary">选择的目录只在本机扫描；Dockyard 不会执行项目脚本或 PM2 配置。</Typography.Paragraph><div className="directory-input"><Input value={path} onChange={onPath} placeholder="项目绝对路径" showClear /><Button icon={<IconFolder />} loading={busy} onClick={onChoose}>选择目录</Button></div>{preview && <div className="preview-list"><div className="preview-heading"><b>{preview.projectName}</b><span>{preview.applications.length} 个可运行候选项</span></div>{preview.applications.map((candidate) => <div className="preview-item" key={candidate.key}><Tag color={candidate.origin === 'pm2-ecosystem' ? 'blue' : 'grey'}>{candidate.origin === 'pm2-ecosystem' ? 'PM2' : 'script'}</Tag><div><b>{candidate.name}</b><code>{[candidate.command.executable, ...candidate.command.args].join(' ')}</code>{candidate.warnings.map((warning) => <Typography.Text type="warning" key={warning.field}>{warning.field}: {warning.reason}</Typography.Text>)}</div></div>)}{preview.applications.length === 0 && <EmptyHint icon={<IconSearch />} title="没有发现可运行候选项" text="请检查 package.json scripts 或 PM2 配置。" />}</div>}</Modal> }

function ApplicationTable({ apps, onAction, projectById }: { apps: Application[]; onAction: (app: Application, operation: 'start' | 'stop' | 'restart') => void; projectById: Map<string, Project> }): ReactElement { return <div className="table-wrap"><table className="app-table"><thead><tr><th>应用</th><th>所属项目</th><th>状态</th><th>命令</th><th /></tr></thead><tbody>{apps.map((app) => <tr key={app.id}><td><b>{app.name}</b><small>{app.cwd}</small></td><td>{projectById.get(app.projectId)?.name ?? '—'}</td><td><StatusTag status={app.status} /></td><td><code>{[app.command.executable, ...app.command.args].join(' ')}</code></td><td className="row-actions"><Button size="small" icon={<IconPlay />} disabled={app.status === 'running'} onClick={() => onAction(app, 'start')}>启动</Button><Button size="small" icon={<IconRefresh />} onClick={() => onAction(app, 'restart')}>重启</Button><Button size="small" type="danger" icon={<IconStop />} disabled={app.status === 'stopped'} onClick={() => onAction(app, 'stop')}>停止</Button></td></tr>)}</tbody></table></div> }
function StatusTag({ status }: { status: Status }): ReactElement { const color = status === 'running' ? 'green' : status === 'crashed' ? 'red' : status === 'restarting' ? 'orange' : 'grey'; return <Tag color={color}>{status}</Tag> }
function StatCard({ label, value, accent, icon }: { label: string; value: string | number; accent: string; icon: ReactElement }): ReactElement { return <div className={`stat-card ${accent}`}><span className="stat-icon">{icon}</span><div><b>{value}</b><small>{label}</small></div></div> }
function EmptyHint({ icon, title, text }: { icon: ReactElement; title: string; text: string }): ReactElement { return <div className="empty-hint"><span>{icon}</span><b>{title}</b><Typography.Text type="tertiary">{text}</Typography.Text></div> }
async function api<T = unknown>(path: string, init: RequestInit = {}): Promise<T> { const response = await fetch(path, { headers: { 'Content-Type': 'application/json', ...init.headers }, ...init }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof body.message === 'string' ? body.message : `HTTP ${response.status}`); return body as T; }
function errorMessage(error: unknown): string { return error instanceof Error ? error.message : '请求失败。'; }
createRoot(document.getElementById('root')!).render(<StrictMode><DockyardApp /></StrictMode>);
